globalThis.ADD2E_EFFECTS_ENGINE_VERSION="2026-05-25-conditional-fixed-ac-v1";
class Add2eEffectsEngine{
static normalizeTag(v){return String(v??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g,"").replace(/\s+/g,"_");}
static normalizeKey(v){return this.normalizeTag(v).replace(/s$/,"");}
static toArray(v){if(!v)return[];if(Array.isArray(v))return v;if(v instanceof Set)return[...v];if(typeof v==="string")return v.split(/[,;\n|]+/).map(s=>s.trim()).filter(Boolean);if(typeof v==="object"){for(const k of["value","tags","list","items","effectTags"]){if(v[k]!==undefined&&v[k]!==null)return this.toArray(v[k]);}}return[];}
static readNumber(...vals){for(const v of vals){if(v===undefined||v===null||v==="")continue;if(typeof v==="object"){const n=this.readNumber(v.value,v.current,v.actuel,v.total,v.max);if(Number.isFinite(n))return n;continue;}const n=Number(String(v).replace(",","."));if(Number.isFinite(n))return n;}return null;}
static addTagsInto(dst,raw){for(const tag of this.toArray(raw)){const t=this.normalizeTag(tag);if(t)dst.push(t);}}
static addEffectTagsInto(dst,e){if(!e)return;this.addTagsInto(dst,e.flags?.add2e?.tags);this.addTagsInto(dst,e.flags?.add2e?.effectTags);if(e.getFlag){try{this.addTagsInto(dst,e.getFlag("add2e","tags"));}catch{}try{this.addTagsInto(dst,e.getFlag("add2e","effectTags"));}catch{}}}
static addEmbeddedItemEffectTagsInto(dst,item){const effects=item?.effects?.contents??item?.effects??[];for(const e of effects){if(!e?.disabled)this.addEffectTagsInto(dst,e);}}
static getActorLevel(actor){const s=actor?.system??{};for(const v of[s.niveau,s.level,s.details?.level,s.details?.niveau]){const n=Number(v);if(Number.isFinite(n)&&n>0)return n;}return 1;}
static itemTags(item){const s=item?.system??{},out=[];for(const v of[item?.name,s.nom,s.categorie,s.category,s.type,s.sousType,s.sous_type,s.famille,s.famille_arme,s.tags,s.tag,s.effectTags,s.effets,s.effects,item?.flags?.add2e?.tags,item?.flags?.add2e?.effectTags])this.addTagsInto(out,v);return[...new Set(out.map(t=>this.normalizeTag(t)).filter(Boolean))];}
static itemText(item){return this.itemTags(item).join(" ");}
static itemEquipped(item){const s=item?.system??{};return s.equipee===true||s.equipped===true||s.portee===true||s.worn===true;}
static isShieldItem(item){const t=this.itemText(item);return t.includes("bouclier")||t.includes("shield");}
static isHelmetItem(item){const t=this.itemText(item);return t.includes("heaume")||t.includes("casque")||t.includes("helmet");}
static bonusFromName(item){const m=String(item?.name??item?.system?.nom??"").match(/\+\s*(\d+)/);return m?Number(m[1])||0:0;}
static looksMagical(item){const s=item?.system??{},t=this.itemText(item);return s.magique===true||s.magic===true||t.includes("magique")||t.includes("magic")||/\+\s*\d+/.test(String(item?.name??""));}
static itemDefenseBonus(item){const s=item?.system??{};let b=Math.abs(this.readNumber(s.bonus_ca,s.bonus_ac,s.ca_bonus,s.ac_bonus,s.protectionBonus,s.protection_bonus)??0);for(const tag of this.itemTags(item)){const m=tag.match(/^(?:bonus_ca|bonus_ac|protection|protection_ca):([+\-]?\d+)$/);if(m)b+=Math.abs(Number(m[1])||0);}if(!b&&this.looksMagical(item)){const type=String(item?.type??"").toLowerCase(),t=this.itemText(item);if(type==="armure"||type==="armor"||t.includes("anneau")||t.includes("bague")||t.includes("cape")||t.includes("protection"))b=this.bonusFromName(item);}return b;}
static itemFixedCA(item){const s=item?.system??{},type=String(item?.type??"").toLowerCase(),text=this.itemText(item);let ca=this.readNumber(s.ca_fixe,s.caFixe,s.fixedCA,s.fixed_ac,s.ac_fixe,s.acFixe);for(const tag of this.itemTags(item)){const m=tag.match(/^(?:ca_fixe|ca_fixe_autres|ac_fixe|fixed_ca|classe_armure):([+\-]?\d+)$/);if(m)ca=Number(m[1]);}if(!Number.isFinite(ca)&&(type==="objet"||type==="object"||type==="equipment")&&(text.includes("bracelet")||text.includes("bracer"))){const m=String(item?.name??s.nom??"").match(/(?:ca|classe\s+d[’']?armure|ac)\s*([\-]?\d+)/i)||String(item?.name??s.nom??"").match(/\b([\-]?\d+)\b\s*$/);if(m)ca=Number(m[1]);}return Number.isFinite(ca)?ca:null;}
static getMagicWeaponBonus(item,kind="hit"){const s=item?.system??{};const n=kind==="damage"?this.readNumber(s.bonus_dom,s.bonus_degats,s.damage_bonus,s.degats_bonus,s.bonusDegats):this.readNumber(s.bonus_hit,s.bonus_toucher,s.hit_bonus,s.attack_bonus,s.bonusAttaque);if(Number.isFinite(n))return n;return this.looksMagical(item)?this.bonusFromName(item):0;}
static equippedItems(actor,types=null){const allowed=types?new Set(types.map(t=>String(t).toLowerCase())):null;return[...(actor?.items??[])].filter(i=>{const type=String(i?.type??"").toLowerCase();return(!allowed||allowed.has(type))&&this.itemEquipped(i);});}
static getDexDefense(actor){const s=actor?.system??{};const direct=this.readNumber(s.dex_def,s.dexDefense,s.dex_defense,s.mod_dex_defense);if(Number.isFinite(direct))return direct;const dex=this.readNumber(s.dexterite,s.dexterite_base,s.dex,s.dexterity)??10;if(dex<=3)return 4;if(dex===4)return 3;if(dex===5)return 2;if(dex===6)return 1;if(dex<=14)return 0;if(dex===15)return-1;if(dex===16)return-2;if(dex===17)return-3;return-4;}
static getMagicPassiveDefense(actor,context={}){const items=this.equippedItems(actor),armors=items.filter(i=>["armure","armor"].includes(String(i.type??"").toLowerCase())),objects=items.filter(i=>!["armure","armor"].includes(String(i.type??"").toLowerCase())),worn=armors.filter(i=>!this.isShieldItem(i)&&!this.isHelmetItem(i)),shields=armors.filter(i=>this.isShieldItem(i)),helmets=armors.filter(i=>this.isHelmetItem(i));let armorBase=10,armorName="Aucune",armorMagicBonus=0;for(const a of worn){const ac=this.readNumber(a.system?.ac,a.system?.ca,a.system?.armorClass,a.system?.base_ca,a.system?.baseAC);if(Number.isFinite(ac)&&ac<armorBase){armorBase=ac;armorName=a.name;armorMagicBonus=this.itemDefenseBonus(a);}}let fixedCA=null,fixedSource="";for(const o of objects){const ca=this.itemFixedCA(o);if(Number.isFinite(ca)&&(fixedCA===null||ca<fixedCA)){fixedCA=ca;fixedSource=o.name;}}const fixedCAActive=Number.isFinite(fixedCA);const baseAfterFixed=fixedCAActive?fixedCA:armorBase;const appliedArmorMagicBonus=fixedCAActive?0:armorMagicBonus;let shieldBonus=0,shieldSources=[];for(const sh of shields){const base=Math.max(1,Math.abs(this.readNumber(sh.system?.ac,sh.system?.ca,sh.system?.armorClass)??1)),mag=this.itemDefenseBonus(sh);shieldBonus+=base+mag;shieldSources.push(`${sh.name}:${base+mag}`);}let helmetBonus=0;for(const h of helmets)helmetBonus+=Math.abs(this.readNumber(h.system?.ac,h.system?.ca,h.system?.armorClass)??0)+this.itemDefenseBonus(h);let objectProtectionBonus=0,objectSources=[];for(const o of objects){if(this.itemFixedCA(o)!==null)continue;const b=this.itemDefenseBonus(o);if(b){objectProtectionBonus+=b;objectSources.push(`${o.name}:${b}`);}}const dex=this.getDexDefense(actor),armorLayerCA=baseAfterFixed-appliedArmorMagicBonus,caNaturel=armorLayerCA+dex-shieldBonus-helmetBonus,caTotal=caNaturel-objectProtectionBonus;return{armorBase,armorName,armorMagicBonus:appliedArmorMagicBonus,ignoredArmorMagicBonus:fixedCAActive?armorMagicBonus:0,fixedCA,fixedSource,fixedCAActive,baseAfterFixed,armorLayerCA,dex,shieldBonus,shieldSources,helmetBonus,objectProtectionBonus,objectSources,caNaturel,caTotal,syntheticArmorAC:armorLayerCA-objectProtectionBonus,context,version:globalThis.ADD2E_EFFECTS_ENGINE_VERSION};}
static addClassFeatureTagsInto(dst,raw,level=1){const arr=Array.isArray(raw)?raw:(raw&&typeof raw==="object"?Object.values(raw):[]);for(const f of arr){if(!f||typeof f!=="object")continue;const min=Number(f.minLevel??f.minimumLevel??f.level??f.niveau??1)||1;if(level<min)continue;for(const v of[f.tags,f.tag,f.effectTags,f.effets,f.effects,f.flags?.add2e?.tags])this.addTagsInto(dst,v);}}
static classFeatureMinLevel(f){const n=Number(f?.minLevel??f?.minimumLevel??f?.niveauMin??f?.level??f?.niveau??1);return Number.isFinite(n)&&n>0?n:1;}
static classFeatureMaxLevel(f){const raw=f?.maxLevel??f?.maximumLevel??f?.niveauMax??f?.max;if(raw===undefined||raw===null||raw==="")return null;const n=Number(raw);return Number.isFinite(n)&&n>0?n:null;}
static isClassFeatureUnlocked(f,l){if(!f||typeof f!=="object")return false;const min=this.classFeatureMinLevel(f),max=this.classFeatureMaxLevel(f);return l>=min&&(max===null||l<=max);}
static normalizeClassFeature(f){return{...foundry.utils.deepClone(f),minLevel:this.classFeatureMinLevel(f),maxLevel:this.classFeatureMaxLevel(f),available:true,activable:f?.activable===true};}
static isClassFeatureActivable(f){return f?.activable===true;}
static getUnlockedClassFeatures(actor){if(!actor)return[];const level=this.getActorLevel(actor),out=[],push=raw=>{const arr=Array.isArray(raw)?raw:(raw&&typeof raw==="object"?Object.values(raw):[]);for(const f of arr)if(this.isClassFeatureUnlocked(f,level))out.push(this.normalizeClassFeature(f));};push(actor.system?.classFeatures);push(actor.system?.details_classe?.classFeaturesDebloquees);push(actor.system?.details_classe?.classFeatures);for(const i of actor.items??[])if(String(i.type||"").toLowerCase()==="classe")push(i.system?.classFeatures);const seen=new Set();return out.filter(f=>{const k=`${f.minLevel}|${f.name??f.label??f.title??f.nom??JSON.stringify(f.tags??[])}`;if(seen.has(k))return false;seen.add(k);return true;});}
static getActiveClassFeatures(actor){return this.getUnlockedClassFeatures(actor).filter(f=>this.isClassFeatureActivable(f));}
static getConstitutionTotal(actor){const s=actor?.system??{},direct=Number(s.constitution);if(!Number.isNaN(direct)&&direct>0)return direct;return Number(s.constitution_base||0)+Number(s.constitution_race??s.bonus_caracteristiques?.constitution??0)+Number(s.constitution_bonus??s.bonus_divers_caracteristiques?.constitution??0);}
static getConstitutionSaveBonus(actor){return Math.max(0,Math.min(5,Math.floor(this.getConstitutionTotal(actor)/3.5)));}
static getRacialTagsForRace(){return[];}
static getRaceSlug(actor){let raw="";const r=actor?.system?.race;if(typeof r==="string")raw=r;else if(r&&typeof r==="object")raw=r.value??r.name??r.label??"";raw=raw||actor?.system?.details_race?.slug||actor?.system?.details_race?.name||actor?.system?.details?.race||actor?.system?.race_nom||actor?.items?.find(i=>String(i.type).toLowerCase()==="race")?.name||"";return String(raw).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g,"").replace(/\s+/g,"-").trim();}
static getActiveTags(actor){if(!actor)return[];const tags=[],level=this.getActorLevel(actor);this.addTagsInto(tags,this.getRacialTagsForRace(this.getRaceSlug(actor)));this.addTagsInto(tags,actor.flags?.add2e?.racialTags);this.addTagsInto(tags,actor.flags?.add2e?.classTags);if(actor.getFlag){try{this.addTagsInto(tags,actor.getFlag("add2e","racialTags"));}catch{}try{this.addTagsInto(tags,actor.getFlag("add2e","classTags"));}catch{}}this.addClassFeatureTagsInto(tags,actor.system?.classFeatures,level);this.addClassFeatureTagsInto(tags,actor.system?.details_classe?.classFeatures,level);for(const e of actor.effects??[]){if(e.disabled)continue;if(e.origin){try{const src=fromUuidSync(e.origin);if(src&&src.parent===actor&&src.system?.equipee===false)continue;}catch{}}this.addEffectTagsInto(tags,e);}for(const item of actor.items??[]){const type=String(item.type||"").toLowerCase(),always=type==="race"||type==="classe",equip=["arme","armure","objet","weapon","armor","equipment","object","magic","objet_magique"].includes(type);if(!always&&!equip)continue;if(equip&&item.system?.equipee!==true)continue;for(const v of[item.system?.tags,item.system?.tag,item.system?.effectTags,item.system?.effets,item.system?.effects,item.flags?.add2e?.tags,item.flags?.add2e?.effectTags])this.addTagsInto(tags,v);this.addEmbeddedItemEffectTagsInto(tags,item);if(always)this.addClassFeatureTagsInto(tags,item.system?.classFeatures,level);if(item.getFlag){try{this.addTagsInto(tags,item.getFlag("add2e","tags"));}catch{}try{this.addTagsInto(tags,item.getFlag("add2e","effectTags"));}catch{}}}const monk=[...(actor.items??[])].find(i=>String(i.type||"").toLowerCase()==="classe"&&(this.normalizeKey(i.system?.label||i.name||"").includes("moine")||this.toArray(i.system?.tags).map(t=>this.normalizeTag(t)).includes("classe:moine")));if(monk){const prog=Array.isArray(monk.system?.monkProgression)&&monk.system.monkProgression.length?monk.system.monkProgression:(Array.isArray(monk.system?.progression)?monk.system.progression:[]),row=prog.find(p=>Number(p?.niveau??p?.level)===level)??prog[Math.max(0,Math.min(prog.length-1,level-1))]??null;this.addTagsInto(tags,row?.tags);}return[...new Set(tags.map(t=>this.normalizeTag(t)).filter(Boolean))];}
static hasTag(actor,tag){return this.getActiveTags(actor).includes(this.normalizeTag(tag));}
static hasImmunity(actor,tag){const wanted=this.normalizeTag(tag),tags=this.getActiveTags(actor);return tags.includes(wanted)||tags.some(t=>t.startsWith("immunite:")&&wanted.includes(this.normalizeTag(t.split(":")[1]||"")));}
static getResistanceAliases(t){const raw=this.normalizeTag(t),s=new Set([raw]);if(["charme","charm","sommeil","sleep","suggestion","charme_suggestion"].includes(raw)){s.add("charme_sommeil");s.add("charme");s.add("sommeil");s.add("suggestion");s.add("charme_suggestion");}if(["esp","perception_extrasensorielle","pensee","pensees"].includes(raw)){s.add("esp");s.add("perception_extrasensorielle");}if(["maladie","disease"].includes(raw)){s.add("maladie");s.add("disease");}return[...s].filter(Boolean);}
static getResistanceInfo(actor,typeResist){const tags=this.getActiveTags(actor),aliases=this.getResistanceAliases(typeResist);for(const a of aliases){const tag=tags.find(t=>t.startsWith(`resistance:${a}:`));if(tag){let pct=Number(tag.split(":")[2])||0;pct=pct>=0&&pct<=1?pct*100:pct;return{found:true,type:String(typeResist??""),matchedType:a,tag,pct:Math.max(0,Math.min(100,pct))};}}return{found:false,type:String(typeResist??""),matchedType:"",tag:"",pct:0};}
static checkResistanceDetails(actor,typeResist,options={}){const info=this.getResistanceInfo(actor,typeResist);if(!info.found){const r={found:false,resiste:false,type:String(typeResist??""),matchedType:"",tag:"",pct:0,jet:0,details:`Aucune résistance contre ${typeResist}`};globalThis.add2eLastResistanceRoll=r;return r;}const jet=Math.ceil(Math.random()*100),resiste=jet<=info.pct,r={found:true,resiste,type:info.type,matchedType:info.matchedType,tag:info.tag,pct:info.pct,jet,details:`Résistance ${info.pct}% contre ${typeResist} : jet ${jet} => ${resiste?"réussite":"échec"}`};globalThis.add2eLastResistanceRoll=r;if(options.chat!==false&&typeof ChatMessage!=="undefined")ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<div class="add2e-chat-card"><b>Résistance</b> ${actor?.name||"Cible"} vs ${typeResist} : ${jet}/${info.pct}% — ${resiste?"réussite":"échec"}</div>`});return r;}
static checkResistance(actor,typeResist,options={}){return this.checkResistanceDetails(actor,typeResist,options).resiste;}
static getCAFixe(actor,context={}){const result=this.getConditionalFixedCA(actor,context);return result.ca;}
static getConditionalFixedCA(actor,context={}){const tags=this.getActiveTags(actor);const frontOnly=tags.includes("condition:attaque_frontale")||tags.includes("condition:frontale")||tags.includes("frontale:oui");if(frontOnly&&context.frontale===false)return{ca:null,applied:false,reason:"not-front",tags,context};const sousType=this.normalizeTag(context.sousType??context.attackSubtype??context.type??"");const candidates=[];const pushTag=(prefix,label)=>{for(const t of tags){if(!t.startsWith(prefix))continue;const v=Number(t.split(":")[1]);if(Number.isFinite(v))candidates.push({ca:v,tag:t,label});}};if(sousType==="projectile_lance")pushTag("ca_fixe_projectile_lance:","projectile lancé à la main");else if(sousType==="projectile_propulse")pushTag("ca_fixe_projectile_propulse:","projectile propulsé");else pushTag("ca_fixe_autres:","attaque frontale");pushTag(`ca_fixe_${sousType}:`,sousType||"conditionnelle");for(const t of tags){if(!t.startsWith("ca_fixe_conditionnelle:"))continue;const parts=t.split(":");if(parts.length>=3&&(parts[1]===sousType||!parts[1])){const v=Number(parts[2]);if(Number.isFinite(v))candidates.push({ca:v,tag:t,label:parts[1]||"conditionnelle"});}}const passive=this.getMagicPassiveDefense(actor,context).fixedCA;if(Number.isFinite(passive))candidates.push({ca:passive,tag:"magic-passive-fixed-ca",label:"CA fixe passive"});if(!candidates.length)return{ca:null,applied:false,reason:"none",tags,context};const best=candidates.sort((a,b)=>a.ca-b.ca)[0];return{ca:best.ca,applied:true,reason:"fixed-ca",sourceTag:best.tag,label:best.label,candidates,tags,context};}
static getCABonus(actor,context={}){const tags=this.getActiveTags(actor);let b=0;for(const t of tags){if(t.startsWith("bonus_ca:"))b+=Number(t.split(":")[1])||0;if(context.type==="magique"&&t.startsWith("bonus_ca_magique:"))b+=Number(t.split(":")[1])||0;if(context.type==="melee"&&t.startsWith("bonus_ca_melee:"))b+=Number(t.split(":")[1])||0;if(context.type==="projectile"&&t.startsWith("bonus_ca_projectile:"))b+=Number(t.split(":")[1])||0;}return b+this.getMagicPassiveDefense(actor,context).objectProtectionBonus;}
static getBonusCAVs(actor,typeAttaquant){const tags=this.getActiveTags(actor),norm=this.normalizeKey(typeAttaquant);let b=0;for(const t of tags){if(!t.startsWith("bonus_ca_vs:"))continue;const[,who,val]=t.split(":");if(this.normalizeKey(who)===norm)b+=Number(val)||0;}return b;}
static getSaveBonusFrontal(actor){let b=0;for(const t of this.getActiveTags(actor))if(t.startsWith("bonus_save_frontal:"))b+=Number(t.split(":")[1])||0;return b;}
static getSaveBonusVs(actor,vsType){if(!actor||!vsType)return 0;let b=0,n=this.normalizeKey(vsType);for(const t of this.getActiveTags(actor)){if(!t.startsWith("bonus_save_vs:"))continue;const p=t.split(":");if(p[2]==="const")continue;if(this.normalizeKey(p[1]||"")&&n.includes(this.normalizeKey(p[1]||"")))b+=Number(p[2])||0;}return b;}
static getBonusSaveConstitution(actor,saveType){const tags=this.getActiveTags(actor),n=this.normalizeKey(saveType),poison=n.includes("poison"),magie=n.includes("magie")||n.includes("magic")||n.includes("sort")||n.includes("baguette")||n.includes("badine")||n.includes("baton")||n.includes("paralysie")||n.includes("petrification")||n.includes("souffle");let b=0;if(poison&&tags.includes("bonus_save_vs:poison:const"))b+=this.getConstitutionSaveBonus(actor);if(magie&&(tags.includes("bonus_save_vs:magie:const")||tags.includes("bonus_save_vs:sort:const")||tags.includes("bonus_save_vs:baguette:const")))b+=this.getConstitutionSaveBonus(actor);return b;}
static getBonusTouche(actor,typeArme){let b=0,n=this.normalizeKey(typeArme);if(!n)return 0;for(const t of this.getActiveTags(actor)){if(!t.startsWith("bonus_touche:"))continue;const[,arme,val]=t.split(":");if(this.normalizeKey(arme)===n)b+=Number(val)||0;}return b;}
static getBonusToucheVs(actor,typeCible){let b=0,n=this.normalizeKey(typeCible);if(!n)return 0;for(const t of this.getActiveTags(actor)){if(!t.startsWith("bonus_touche_vs:"))continue;const[,c,val]=t.split(":");if(this.normalizeKey(c)===n)b+=Number(val)||0;}return b;}
static getActorClassSystem(actor){return actor?.items?.find?.(i=>String(i.type||"").toLowerCase()==="classe")?.system??actor?.system?.details_classe??null;}
static isMonk(actor){const cls=this.getActorClassSystem(actor),label=this.normalizeKey(cls?.label||cls?.name||cls?.nom||actor?.system?.classe||"");return label.includes("moine")||this.hasTag(actor,"classe:moine");}
static getClassProgressionEntry(actor,field="progression"){const cls=this.getActorClassSystem(actor),level=this.getActorLevel(actor),p=cls?.[field]??cls?.progression??[];if(!Array.isArray(p)||!p.length)return null;return p.find(x=>Number(x?.niveau??x?.level)===level)??p[Math.max(0,Math.min(p.length-1,level-1))]??null;}
static getMonkProgression(actor){return this.isMonk(actor)?this.getClassProgressionEntry(actor,"monkProgression")??this.getClassProgressionEntry(actor,"progression"):null;}
static getMonkArmorClass(actor){const v=Number(this.getMonkProgression(actor)?.monkAC??this.getMonkProgression(actor)?.caMoine??this.getMonkProgression(actor)?.ca_moine);return Number.isFinite(v)?v:null;}
static getMonkMove(actor){const p=this.getMonkProgression(actor),v=Number(p?.move??p?.movement??p?.mouvement);return Number.isFinite(v)?v:null;}
static getMonkOpenDoors(actor){const p=this.getMonkProgression(actor),v=Number(p?.openDoors??p?.ouvrir_portes);return Number.isFinite(v)?v:null;}
static getMonkUnarmedDamage(actor){const p=this.getMonkProgression(actor);return String(p?.unarmedDamage??p?.main_nue??p?.damage??"").trim();}
static getMonkAttacksPerRound(actor){const p=this.getMonkProgression(actor);return String(p?.attacksPerRound??p?.attaquesParRound??"").trim();}
static getMonkStunParalyze(actor){const p=this.getMonkProgression(actor),v=Number(p?.stunParalyze??p?.etourdissement??p?.paralysie);return Number.isFinite(v)?v:0;}
static getMonkSlowFall(actor){const p=this.getMonkProgression(actor),v=Number(p?.slowFall??p?.chute_ralentie);return Number.isFinite(v)?v:0;}
static getMonkSelfHealPerDay(actor){const p=this.getMonkProgression(actor),v=Number(p?.selfHealPerDay??p?.auto_soin);return Number.isFinite(v)?v:0;}
static getMonkWeaponDamageBonus(actor){const p=this.getMonkProgression(actor),v=Number(p?.monkWeaponDamageBonus??p?.bonusDegatsArme??p?.bonus_degats_arme);return Number.isFinite(v)?v:(this.isMonk(actor)?Math.floor(this.getActorLevel(actor)/2):0);}
static hasMonkDiseaseImmunity(actor){return this.hasImmunity(actor,"maladie");}
static getMonkProgressionTags(actor){const p=this.getMonkProgression(actor);return p?this.toArray(p.tags).map(t=>this.normalizeTag(t)).filter(Boolean):[];}
static getMonkResistCharmSuggestion(actor){const p=this.getMonkProgression(actor),v=Number(p?.resistCharmSuggestion??p?.resistance_charme_suggestion);return Number.isFinite(v)?v:0;}
static getMonkResistESP(actor){const p=this.getMonkProgression(actor),v=Number(p?.resistESP??p?.resistance_esp);return Number.isFinite(v)?v:0;}
static hasMonkQuiveringPalm(actor){const p=this.getMonkProgression(actor);return!!p?.quiveringPalm||this.hasTag(actor,"moine:paume_palpitante")||this.hasTag(actor,"paume_palpitante");}
static getMonkSummary(actor){const p=this.getMonkProgression(actor);if(!p)return null;return{level:this.getActorLevel(actor),title:p.title??"",armorClass:this.getMonkArmorClass(actor),move:this.getMonkMove(actor),openDoors:this.getMonkOpenDoors(actor),unarmedDamage:this.getMonkUnarmedDamage(actor),weaponDamageBonus:this.getMonkWeaponDamageBonus(actor),attacksPerRound:this.getMonkAttacksPerRound(actor),stunParalyze:this.getMonkStunParalyze(actor),slowFall:this.getMonkSlowFall(actor),selfHealPerDay:this.getMonkSelfHealPerDay(actor),resistCharmSuggestion:this.getMonkResistCharmSuggestion(actor),resistESP:this.getMonkResistESP(actor),quiveringPalm:this.hasMonkQuiveringPalm(actor),activeCapabilities:this.getActiveClassFeatures(actor)}}
static analyze(actor,action){const tags=this.getActiveTags(actor),out={};if(action.type==="spell"&&String(action.name||"").toLowerCase().includes("missile magique")&&tags.includes("immunite:missile_magique"))out.immunise=true;if(action.type==="attaque"){const fixed=this.getConditionalFixedCA(actor,{sousType:action.sousType,frontale:!!action.frontale,type:action.type,source:action.source});if(fixed.ca!==null)out.ca_fixe=fixed.ca;out.ca_fixe_details=fixed;out.bonus_ca=this.getCABonus(actor,action);}if(action.type==="save"){let b=0;if(action.frontale)b+=this.getSaveBonusFrontal(actor);if(action.vsType)b+=this.getSaveBonusVs(actor,action.vsType)+this.getBonusSaveConstitution(actor,action.vsType);if(b!==0)out.bonus_save=(out.bonus_save||0)+b;}if(action.type==="moine"||action.type==="monk")out.moine=this.getMonkSummary(actor);if(tags.includes("camouflage"))out.camouflage=true;return out;}
static getInfravision(actor){let best=0;for(const t of this.getActiveTags(actor)){if(!t.startsWith("infravision:"))continue;const v=Number(t.split(":")[1])||0;if(v>best)best=v;}return best;}
}
globalThis.Add2eEffectsEngine=Add2eEffectsEngine;
