globalThis.ADD2E_EFFECTS_ENGINE_VERSION="2026-06-30-damage-resolution-v1";

class Add2eEffectsEngine {
  static normalizeTag(v) { return String(v ?? "").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[’']/g, "").replace(/\s+/g, "_"); }
  static normalizeKey(v) { return this.normalizeTag(v).replace(/s$/, ""); }
  static toArray(v) { if (!v) return []; if (Array.isArray(v)) return v; if (v instanceof Set) return [...v]; if (typeof v === "string") return v.split(/[,;\n|]+/).map(s => s.trim()).filter(Boolean); if (typeof v === "object") for (const k of ["value", "tags", "list", "items", "effectTags"]) if (v[k] !== undefined && v[k] !== null) return this.toArray(v[k]); return []; }
  static readNumber(...vals) { for (const v of vals) { if (v === undefined || v === null || v === "") continue; if (typeof v === "object") { const n = this.readNumber(v.value, v.current, v.actuel, v.total, v.max); if (Number.isFinite(n)) return n; continue; } const n = Number(String(v).replace(",", ".")); if (Number.isFinite(n)) return n; } return null; }
  static addTagsInto(dst, raw) { if (!dst) return; const add = typeof dst.add === "function" ? value => dst.add(value) : typeof dst.push === "function" ? value => dst.push(value) : null; if (!add) return; for (const tag of this.toArray(raw)) { const normalized = this.normalizeTag(tag); if (normalized) add(normalized); } }
  static addEffectTagsInto(dst, effect) { if (!effect) return; this.addTagsInto(dst, effect.flags?.add2e?.tags); this.addTagsInto(dst, effect.flags?.add2e?.effectTags); if (!effect.getFlag) return; try { this.addTagsInto(dst, effect.getFlag("add2e", "tags")); } catch {} try { this.addTagsInto(dst, effect.getFlag("add2e", "effectTags")); } catch {} }
  static addEmbeddedItemEffectTagsInto(dst, item) { const effects = item?.effects?.contents ?? item?.effects ?? []; for (const effect of effects) if (!effect?.disabled) this.addEffectTagsInto(dst, effect); }
  static getActorLevel(actor) { const system = actor?.system ?? {}; for (const value of [system.niveau, system.level, system.details?.level, system.details?.niveau]) { const level = Number(value); if (Number.isFinite(level) && level > 0) return level; } return 1; }
  static itemTags(item) { const system = item?.system ?? {}, out = []; for (const value of [item?.name, system.nom, system.categorie, system.category, system.type, system.sousType, system.sous_type, system.famille, system.famille_arme, system.tags, system.tag, system.effectTags, system.effets, system.effects, item?.flags?.add2e?.tags, item?.flags?.add2e?.effectTags]) this.addTagsInto(out, value); return [...new Set(out.map(tag => this.normalizeTag(tag)).filter(Boolean))]; }
  static itemText(item) { return this.itemTags(item).join(" "); }
  static itemEquipped(item) { const system = item?.system ?? {}; return system.equipee === true || system.equipped === true || system.portee === true || system.worn === true; }
  static isShieldItem(item) { const text = this.itemText(item); return text.includes("bouclier") || text.includes("shield"); }
  static isHelmetItem(item) { const text = this.itemText(item); return text.includes("heaume") || text.includes("casque") || text.includes("helmet"); }
  static bonusFromName(item) { const match = String(item?.name ?? item?.system?.nom ?? "").match(/\+\s*(\d+)/); return match ? Number(match[1]) || 0 : 0; }
  static looksMagical(item) { const system = item?.system ?? {}, text = this.itemText(item); return system.magique === true || system.magic === true || text.includes("magique") || text.includes("magic") || /\+\s*\d+/.test(String(item?.name ?? "")); }
  static itemDefenseBonus(item) { const system = item?.system ?? {}; let bonus = Math.abs(this.readNumber(system.bonus_ca, system.bonus_ac, system.ca_bonus, system.ac_bonus, system.protectionBonus, system.protection_bonus) ?? 0); for (const tag of this.itemTags(item)) { const match = tag.match(/^(?:bonus_ca|bonus_ac|protection|protection_ca):([+\-]?\d+)$/); if (match) bonus += Math.abs(Number(match[1]) || 0); } if (!bonus && this.looksMagical(item)) { const type = String(item?.type ?? "").toLowerCase(), text = this.itemText(item); if (type === "armure" || type === "armor" || text.includes("anneau") || text.includes("bague") || text.includes("cape") || text.includes("protection")) bonus = this.bonusFromName(item); } return bonus; }
  static itemFixedCA(item) { const system = item?.system ?? {}, type = String(item?.type ?? "").toLowerCase(), text = this.itemText(item); let ca = this.readNumber(system.ca_fixe, system.caFixe, system.fixedCA, system.fixed_ac, system.ac_fixe, system.acFixe); for (const tag of this.itemTags(item)) { const match = tag.match(/^(?:ca_fixe|ca_fixe_autres|ac_fixe|fixed_ca|classe_armure):([+\-]?\d+)$/); if (match) ca = Number(match[1]); } if (!Number.isFinite(ca) && (type === "objet" || type === "object" || type === "equipment") && (text.includes("bracelet") || text.includes("bracer"))) { const match = String(item?.name ?? system.nom ?? "").match(/(?:ca|classe\s+d[’']?armure|ac)\s*([\-]?\d+)/i) || String(item?.name ?? system.nom ?? "").match(/\b([\-]?\d+)\b\s*$/); if (match) ca = Number(match[1]); } return Number.isFinite(ca) ? ca : null; }
  static getMagicWeaponBonus(item, kind = "hit") { const system = item?.system ?? {}; const value = kind === "damage" ? this.readNumber(system.bonus_dom, system.bonus_degats, system.damage_bonus, system.degats_bonus, system.bonusDegats) : this.readNumber(system.bonus_hit, system.bonus_toucher, system.hit_bonus, system.attack_bonus, system.bonusAttaque); if (Number.isFinite(value)) return value; return this.looksMagical(item) ? this.bonusFromName(item) : 0; }
  static equippedItems(actor, types = null) { const allowed = types ? new Set(types.map(type => String(type).toLowerCase())) : null; return [...(actor?.items ?? [])].filter(item => { const type = String(item?.type ?? "").toLowerCase(); return (!allowed || allowed.has(type)) && this.itemEquipped(item); }); }
  static getDexDefense(actor) { const system = actor?.system ?? {}, direct = this.readNumber(system.dex_def, system.dexDefense, system.dex_defense, system.mod_dex_defense); if (Number.isFinite(direct)) return direct; const dex = this.readNumber(system.dexterite, system.dexterite_base, system.dex, system.dexterity) ?? 10; if (dex <= 3) return 4; if (dex === 4) return 3; if (dex === 5) return 2; if (dex === 6) return 1; if (dex <= 14) return 0; if (dex === 15) return -1; if (dex === 16) return -2; if (dex === 17) return -3; return -4; }
  static getMagicPassiveDefense(actor, context = {}) { const items = this.equippedItems(actor), armors = items.filter(item => ["armure", "armor"].includes(String(item.type ?? "").toLowerCase())), objects = items.filter(item => !["armure", "armor"].includes(String(item.type ?? "").toLowerCase())), worn = armors.filter(item => !this.isShieldItem(item) && !this.isHelmetItem(item)), shields = armors.filter(item => this.isShieldItem(item)), helmets = armors.filter(item => this.isHelmetItem(item)); let armorBase = 10, armorName = "Aucune", armorMagicBonus = 0; for (const armor of worn) { const ac = this.readNumber(armor.system?.ac, armor.system?.ca, armor.system?.armorClass, armor.system?.base_ca, armor.system?.baseAC); if (Number.isFinite(ac) && ac < armorBase) { armorBase = ac; armorName = armor.name; armorMagicBonus = this.itemDefenseBonus(armor); } } let fixedCA = null, fixedSource = ""; for (const object of objects) { const ca = this.itemFixedCA(object); if (Number.isFinite(ca) && (fixedCA === null || ca < fixedCA)) { fixedCA = ca; fixedSource = object.name; } } const fixedCAActive = Number.isFinite(fixedCA), baseAfterFixed = fixedCAActive ? fixedCA : armorBase, appliedArmorMagicBonus = fixedCAActive ? 0 : armorMagicBonus; let shieldBonus = 0, helmetBonus = 0, objectProtectionBonus = 0; const shieldSources = [], objectSources = []; for (const shield of shields) { const base = Math.max(1, Math.abs(this.readNumber(shield.system?.ac, shield.system?.ca, shield.system?.armorClass) ?? 1)), magic = this.itemDefenseBonus(shield); shieldBonus += base + magic; shieldSources.push(`${shield.name}:${base + magic}`); } for (const helmet of helmets) helmetBonus += Math.abs(this.readNumber(helmet.system?.ac, helmet.system?.ca, helmet.system?.armorClass) ?? 0) + this.itemDefenseBonus(helmet); for (const object of objects) { if (this.itemFixedCA(object) !== null) continue; const bonus = this.itemDefenseBonus(object); if (bonus) { objectProtectionBonus += bonus; objectSources.push(`${object.name}:${bonus}`); } } const dex = this.getDexDefense(actor), armorLayerCA = baseAfterFixed - appliedArmorMagicBonus, caNaturel = armorLayerCA + dex - shieldBonus - helmetBonus, caTotal = caNaturel - objectProtectionBonus; return { armorBase, armorName, armorMagicBonus: appliedArmorMagicBonus, ignoredArmorMagicBonus: fixedCAActive ? armorMagicBonus : 0, fixedCA, fixedSource, fixedCAActive, baseAfterFixed, armorLayerCA, dex, shieldBonus, shieldSources, helmetBonus, objectProtectionBonus, objectSources, caNaturel, caTotal, syntheticArmorAC: armorLayerCA - objectProtectionBonus, context, version: globalThis.ADD2E_EFFECTS_ENGINE_VERSION }; }
  static addClassFeatureTagsInto(dst, raw, level = 1) { const entries = Array.isArray(raw) ? raw : (raw && typeof raw === "object" ? Object.values(raw) : []); for (const feature of entries) { if (!feature || typeof feature !== "object") continue; const minimum = Number(feature.minLevel ?? feature.minimumLevel ?? feature.level ?? feature.niveau ?? 1) || 1; if (level < minimum) continue; for (const value of [feature.tags, feature.tag, feature.effectTags, feature.effets, feature.effects, feature.flags?.add2e?.tags]) this.addTagsInto(dst, value); } }
  static classFeatureMinLevel(feature) { const value = Number(feature?.minLevel ?? feature?.minimumLevel ?? feature?.niveauMin ?? feature?.level ?? feature?.niveau ?? 1); return Number.isFinite(value) && value > 0 ? value : 1; }
  static classFeatureMaxLevel(feature) { const raw = feature?.maxLevel ?? feature?.maximumLevel ?? feature?.niveauMax ?? feature?.max; if (raw === undefined || raw === null || raw === "") return null; const value = Number(raw); return Number.isFinite(value) && value > 0 ? value : null; }
  static isClassFeatureUnlocked(feature, level) { if (!feature || typeof feature !== "object") return false; const min = this.classFeatureMinLevel(feature), max = this.classFeatureMaxLevel(feature); return level >= min && (max === null || level <= max); }
  static normalizeClassFeature(feature) { return { ...foundry.utils.deepClone(feature), minLevel: this.classFeatureMinLevel(feature), maxLevel: this.classFeatureMaxLevel(feature), available: true, activable: feature?.activable === true }; }
  static isClassFeatureActivable(feature) { return feature?.activable === true; }
  static getUnlockedClassFeatures(actor) { if (!actor) return []; const level = this.getActorLevel(actor), out = [], push = raw => { const entries = Array.isArray(raw) ? raw : (raw && typeof raw === "object" ? Object.values(raw) : []); for (const feature of entries) if (this.isClassFeatureUnlocked(feature, level)) out.push(this.normalizeClassFeature(feature)); }; push(actor.system?.classFeatures); push(actor.system?.details_classe?.classFeaturesDebloquees); push(actor.system?.details_classe?.classFeatures); for (const item of actor.items ?? []) if (String(item.type || "").toLowerCase() === "classe") push(item.system?.classFeatures); const seen = new Set(); return out.filter(feature => { const key = `${feature.minLevel}|${feature.name ?? feature.label ?? feature.title ?? feature.nom ?? JSON.stringify(feature.tags ?? [])}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
  static getActiveClassFeatures(actor) { return this.getUnlockedClassFeatures(actor).filter(feature => this.isClassFeatureActivable(feature)); }
  static getConstitutionTotal(actor) { const system = actor?.system ?? {}, direct = Number(system.constitution); if (!Number.isNaN(direct) && direct > 0) return direct; return Number(system.constitution_base || 0) + Number(system.constitution_race ?? system.bonus_caracteristiques?.constitution ?? 0) + Number(system.constitution_bonus ?? system.bonus_divers_caracteristiques?.constitution ?? 0); }
  static getConstitutionSaveBonus(actor) { return Math.max(0, Math.min(5, Math.floor(this.getConstitutionTotal(actor) / 3.5))); }
  static getRacialTagsForRace() { return []; }
  static getRaceSlug(actor) { let raw = "", race = actor?.system?.race; if (typeof race === "string") raw = race; else if (race && typeof race === "object") raw = race.value ?? race.name ?? race.label ?? ""; raw = raw || actor?.system?.details_race?.slug || actor?.system?.details_race?.name || actor?.system?.details?.race || actor?.system?.race_nom || actor?.items?.find(item => String(item.type).toLowerCase() === "race")?.name || ""; return String(raw).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[’']/g, "").replace(/\s+/g, "-").trim(); }
  static getActiveTags(actor) { if (!actor) return []; const tags = [], level = this.getActorLevel(actor); this.addTagsInto(tags, this.getRacialTagsForRace(this.getRaceSlug(actor))); this.addTagsInto(tags, actor.flags?.add2e?.racialTags); this.addTagsInto(tags, actor.flags?.add2e?.classTags); if (actor.getFlag) { try { this.addTagsInto(tags, actor.getFlag("add2e", "racialTags")); } catch {} try { this.addTagsInto(tags, actor.getFlag("add2e", "classTags")); } catch {} } this.addClassFeatureTagsInto(tags, actor.system?.classFeatures, level); this.addClassFeatureTagsInto(tags, actor.system?.details_classe?.classFeatures, level); for (const effect of actor.effects ?? []) { if (effect.disabled) continue; if (effect.origin) { try { const source = fromUuidSync(effect.origin); if (source && source.parent === actor && source.system?.equipee === false) continue; } catch {} } this.addEffectTagsInto(tags, effect); } for (const item of actor.items ?? []) { const type = String(item.type || "").toLowerCase(), always = type === "race" || type === "classe", equippedTypes = ["arme", "armure", "objet", "weapon", "armor", "equipment", "object", "magic", "objet_magique"]; if (!always && !equippedTypes.includes(type)) continue; if (equippedTypes.includes(type) && item.system?.equipee !== true) continue; for (const value of [item.system?.tags, item.system?.tag, item.system?.effectTags, item.system?.effets, item.system?.effects, item.flags?.add2e?.tags, item.flags?.add2e?.effectTags]) this.addTagsInto(tags, value); this.addEmbeddedItemEffectTagsInto(tags, item); if (always) this.addClassFeatureTagsInto(tags, item.system?.classFeatures, level); if (item.getFlag) { try { this.addTagsInto(tags, item.getFlag("add2e", "tags")); } catch {} try { this.addTagsInto(tags, item.getFlag("add2e", "effectTags")); } catch {} } } const monk = [...(actor.items ?? [])].find(item => String(item.type || "").toLowerCase() === "classe" && (this.normalizeKey(item.system?.label || item.name || "").includes("moine") || this.toArray(item.system?.tags).map(tag => this.normalizeTag(tag)).includes("classe:moine"))); if (monk) { const progression = Array.isArray(monk.system?.monkProgression) && monk.system.monkProgression.length ? monk.system.monkProgression : (Array.isArray(monk.system?.progression) ? monk.system.progression : []); const row = progression.find(entry => Number(entry?.niveau ?? entry?.level) === level) ?? progression[Math.max(0, Math.min(progression.length - 1, level - 1))] ?? null; this.addTagsInto(tags, row?.tags); } return [...new Set(tags.map(tag => this.normalizeTag(tag)).filter(Boolean))]; }
  static getContextTags(subject) { if (!subject) return []; const tags = [], system = subject.system ?? {}; for (const raw of [system.tags, system.tag, system.effectTags, system.effets, system.effects, system.race, system.type, system.type_monstre, system.categorie, system.alignement, system.alignment, system.details?.alignment, subject.flags?.add2e?.tags, subject.flags?.add2e?.effectTags]) this.addTagsInto(tags, raw); this.addTagsInto(tags, this.getActiveTags(subject)); return [...new Set(tags.map(tag => this.normalizeTag(tag)).filter(Boolean))]; }
  static toRules(raw) { if (Array.isArray(raw)) return raw.filter(rule => rule && typeof rule === "object"); if (raw && typeof raw === "object") return Array.isArray(raw.rules) ? raw.rules.filter(rule => rule && typeof rule === "object") : [raw]; return []; }
  static getActiveRules(actor) { const rules = [], effects = actor?.effects?.contents ?? actor?.effects ?? []; for (const effect of effects) { if (!effect || effect.disabled) continue; const raws = [effect.flags?.add2e?.rules]; if (effect.getFlag) try { raws.push(effect.getFlag("add2e", "rules")); } catch {} for (const raw of raws) for (const rule of this.toRules(raw)) rules.push({ ...rule, source: { effectId: effect.id ?? null, effectName: effect.name ?? "" } }); } return rules; }
  static ruleTags(raw) { return this.toArray(raw).map(tag => this.normalizeTag(tag)).filter(Boolean); }
  static evaluateActionRules(actor, action = {}) { const actionType = this.normalizeKey(action?.type ?? ""), subjectTags = new Set(this.ruleTags(action?.subjectTags ?? action?.actorTags)), actionTags = new Set(this.ruleTags(action?.actionTags)), matchedRules = []; for (const rule of this.getActiveRules(actor)) { if (this.normalizeTag(rule.kind) !== "block_action") continue; const actions = this.ruleTags(rule.actions ?? rule.action); if (actions.length && !actions.includes(actionType)) continue; if (rule.requireContact === true && action?.contact !== true) continue; const subjectAny = this.ruleTags(rule.subjectAnyTags), subjectAll = this.ruleTags(rule.subjectAllTags), actionAny = this.ruleTags(rule.actionAnyTags), actionAll = this.ruleTags(rule.actionAllTags); if (subjectAny.length && !subjectAny.some(tag => subjectTags.has(tag))) continue; if (subjectAll.length && !subjectAll.every(tag => subjectTags.has(tag))) continue; if (actionAny.length && !actionAny.some(tag => actionTags.has(tag))) continue; if (actionAll.length && !actionAll.every(tag => actionTags.has(tag))) continue; matchedRules.push({ kind: "block_action", label: String(rule.label ?? "Action bloquée par un effet actif."), source: rule.source ?? null, rule }); } return { allowed: matchedRules.length === 0, blocked: matchedRules.length > 0, matchedRules, details: matchedRules.map(entry => entry.label) }; }
  static hasTag(actor, tag) { return this.getActiveTags(actor).includes(this.normalizeTag(tag)); }
  static hasImmunity(actor, tag) { const wanted = this.normalizeTag(tag), tags = this.getActiveTags(actor); return tags.includes(wanted) || tags.some(current => current.startsWith("immunite:") && wanted.includes(this.normalizeTag(current.split(":")[1] || ""))); }
  static getResistanceAliases(type) { const raw = this.normalizeTag(type), aliases = new Set([raw]); if (["charme", "charm", "sommeil", "sleep", "suggestion", "charme_suggestion"].includes(raw)) for (const value of ["charme_sommeil", "charme", "sommeil", "suggestion", "charme_suggestion"]) aliases.add(value); if (["esp", "perception_extrasensorielle", "pensee", "pensees"].includes(raw)) { aliases.add("esp"); aliases.add("perception_extrasensorielle"); } if (["maladie", "disease"].includes(raw)) { aliases.add("maladie"); aliases.add("disease"); } return [...aliases].filter(Boolean); }
  static getResistanceInfo(actor, typeResist) { const tags = this.getActiveTags(actor), aliases = this.getResistanceAliases(typeResist); for (const alias of aliases) { const tag = tags.find(current => current.startsWith(`resistance:${alias}:`)); if (!tag) continue; let pct = Number(tag.split(":")[2]) || 0; pct = pct >= 0 && pct <= 1 ? pct * 100 : pct; return { found: true, type: String(typeResist ?? ""), matchedType: alias, tag, pct: Math.max(0, Math.min(100, pct)) }; } return { found: false, type: String(typeResist ?? ""), matchedType: "", tag: "", pct: 0 }; }
  static checkResistanceDetails(actor, typeResist, options = {}) { const info = this.getResistanceInfo(actor, typeResist); if (!info.found) { const result = { found: false, resiste: false, type: String(typeResist ?? ""), matchedType: "", tag: "", pct: 0, jet: 0, details: `Aucune résistance contre ${typeResist}` }; globalThis.add2eLastResistanceRoll = result; return result; } const jet = Math.ceil(Math.random() * 100), resiste = jet <= info.pct, result = { found: true, resiste, type: info.type, matchedType: info.matchedType, tag: info.tag, pct: info.pct, jet, details: `Résistance ${info.pct}% contre ${typeResist} : jet ${jet} => ${resiste ? "réussite" : "échec"}` }; globalThis.add2eLastResistanceRoll = result; if (options.chat !== false && typeof ChatMessage !== "undefined") ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor }), content: `<div class="add2e-chat-card"><b>Résistance</b> ${actor?.name || "Cible"} vs ${typeResist} : ${jet}/${info.pct}% — ${resiste ? "réussite" : "échec"}</div>` }); return result; }
  static checkResistance(actor, typeResist, options = {}) { return this.checkResistanceDetails(actor, typeResist, options).resiste; }
  static getCAFixe(actor, context = {}) { return this.getConditionalFixedCA(actor, context).ca; }
  static getConditionalFixedCA(actor, context = {}) { const tags = this.getActiveTags(actor), frontOnly = tags.includes("condition:attaque_frontale") || tags.includes("condition:frontale") || tags.includes("frontale:oui"); if (frontOnly && context.frontale === false) return { ca: null, applied: false, reason: "not-front", tags, context }; const sousType = this.normalizeTag(context.sousType ?? context.attackSubtype ?? context.type ?? ""), candidates = [], pushTag = (prefix, label) => { for (const tag of tags) { if (!tag.startsWith(prefix)) continue; const value = Number(tag.split(":")[1]); if (Number.isFinite(value)) candidates.push({ ca: value, tag, label }); } }; if (sousType === "projectile_lance") pushTag("ca_fixe_projectile_lance:", "projectile lancé à la main"); else if (sousType === "projectile_propulse") pushTag("ca_fixe_projectile_propulse:", "projectile propulsé"); else pushTag("ca_fixe_autres:", "attaque frontale"); pushTag(`ca_fixe_${sousType}:`, sousType || "conditionnelle"); for (const tag of tags) { if (!tag.startsWith("ca_fixe_conditionnelle:")) continue; const parts = tag.split(":"); if (parts.length >= 3 && (parts[1] === sousType || !parts[1])) { const value = Number(parts[2]); if (Number.isFinite(value)) candidates.push({ ca: value, tag, label: parts[1] || "conditionnelle" }); } } const passive = this.getMagicPassiveDefense(actor, context).fixedCA; if (Number.isFinite(passive)) candidates.push({ ca: passive, tag: "magic-passive-fixed-ca", label: "CA fixe passive" }); if (!candidates.length) return { ca: null, applied: false, reason: "none", tags, context }; const best = candidates.sort((a, b) => a.ca - b.ca)[0]; return { ca: best.ca, applied: true, reason: "fixed-ca", sourceTag: best.tag, label: best.label, candidates, tags, context }; }
  static getCABonus(actor, context = {}) { let bonus = 0; for (const tag of this.getActiveTags(actor)) { if (tag.startsWith("bonus_ca:")) bonus += Number(tag.split(":")[1]) || 0; if (context.type === "magique" && tag.startsWith("bonus_ca_magique:")) bonus += Number(tag.split(":")[1]) || 0; if (context.type === "melee" && tag.startsWith("bonus_ca_melee:")) bonus += Number(tag.split(":")[1]) || 0; if (context.type === "projectile" && tag.startsWith("bonus_ca_projectile:")) bonus += Number(tag.split(":")[1]) || 0; } return bonus + this.getMagicPassiveDefense(actor, context).objectProtectionBonus; }
  static getBonusCAVs(actor, typeAttaquant) { const normalized = this.normalizeKey(typeAttaquant); let bonus = 0; for (const tag of this.getActiveTags(actor)) { if (!tag.startsWith("bonus_ca_vs:")) continue; const [, type, value] = tag.split(":"); if (this.normalizeKey(type) === normalized) bonus += Number(value) || 0; } return bonus; }
  static getSaveBonusFrontal(actor) { let bonus = 0; for (const tag of this.getActiveTags(actor)) if (tag.startsWith("bonus_save_frontal:")) bonus += Number(tag.split(":")[1]) || 0; return bonus; }
  static getSaveBonusVs(actor, vsType) { if (!actor || !vsType) return 0; let bonus = 0, normalized = this.normalizeKey(vsType); for (const tag of this.getActiveTags(actor)) { if (tag.startsWith("bonus_save:")) { bonus += Number(tag.split(":")[1]) || 0; continue; } if (!tag.startsWith("bonus_save_vs:")) continue; const parts = tag.split(":"), type = this.normalizeKey(parts[1] || ""); if (parts[2] === "const") continue; if (type === "tout" || type === "all" || (type && normalized.includes(type))) bonus += Number(parts[2]) || 0; } return bonus; }
  static getBonusSaveConstitution(actor, saveType) { const tags = this.getActiveTags(actor), normalized = this.normalizeKey(saveType), poison = normalized.includes("poison"), magic = normalized.includes("magie") || normalized.includes("magic") || normalized.includes("sort") || normalized.includes("baguette") || normalized.includes("badine") || normalized.includes("baton") || normalized.includes("paralysie") || normalized.includes("petrification") || normalized.includes("souffle"); let bonus = 0; if (poison && tags.includes("bonus_save_vs:poison:const")) bonus += this.getConstitutionSaveBonus(actor); if (magic && (tags.includes("bonus_save_vs:magie:const") || tags.includes("bonus_save_vs:sort:const") || tags.includes("bonus_save_vs:baguette:const"))) bonus += this.getConstitutionSaveBonus(actor); return bonus; }
  static getDamageContext(type = "", details = "") { const raw = `${String(type ?? "")} ${String(details ?? "")}`, normalized = this.normalizeTag(raw), typeKey = this.normalizeTag(type), detailKey = this.normalizeTag(details), cold = typeKey.includes("froid") || typeKey.includes("cold") || detailKey.includes("froid") || detailKey.includes("cold"), fire = typeKey.includes("feu") || typeKey.includes("fire") || detailKey.includes("feu") || detailKey.includes("fire"), element = cold ? "froid" : fire ? "feu" : "", natural = element === "froid" && (normalized.includes("froid_naturel") || normalized.includes("cold_natural") || normalized.includes("froidnaturel")), temperatureMatch = raw.match(/(?:temperature|temp)\s*[:=]\s*(-?\d+(?:[.,]\d+)?)/i), temperature = temperatureMatch ? Number(String(temperatureMatch[1]).replace(",", ".")) : null; return { element, natural, temperature, raw, normalized }; }
  static getNaturalTemperatureLimit(tags, element) { for (const tag of tags) { const match = tag.match(new RegExp(`^temperature:${element}_naturel:(-?\\d+(?:\\.\\d+)?)$`)); if (match) return Number(match[1]); } return null; }
  static getDamageReductionFactor(value, fallback) { const normalized = this.normalizeTag(value); if (["annule", "zero", "0"].includes(normalized)) return 0; if (["quart", "quarter", "25", "0_25"].includes(normalized)) return 0.25; if (["moitie", "half", "50", "0_5"].includes(normalized)) return 0.5; const numeric = Number(String(value).replace(",", ".")); if (Number.isFinite(numeric) && numeric >= 0 && numeric <= 1) return numeric; if (Number.isFinite(numeric) && numeric > 1 && numeric <= 100) return numeric / 100; return fallback; }
  static getDamageResistanceRule(actor, element) { if (!actor || !element) return { found: false }; const tags = this.getActiveTags(actor), active = tags.includes(`resistance:${element}`) || tags.includes(`etat:resistance_${element}`) || tags.includes(`sort:resistance_au_${element}`) || tags.includes(`damage:resistance:${element}`); if (!active) return { found: false, tags }; const failedTag = tags.find(tag => tag.startsWith(`reduction_degats:${element}:echec:`)) ?? tags.find(tag => tag.startsWith(`degats_${element}_si_save_rate:`)) ?? "", succeededTag = tags.find(tag => tag.startsWith(`reduction_degats:${element}:reussite:`)) ?? tags.find(tag => tag.startsWith(`degats_${element}_si_save_reussi:`)) ?? ""; return { found: true, tags, element, bonus: this.getSaveBonusVs(actor, element), failedMultiplier: this.getDamageReductionFactor(failedTag.split(":").at(-1), 0.5), succeededMultiplier: this.getDamageReductionFactor(succeededTag.split(":").at(-1), 0.25) }; }
  static getDamageSaveThreshold(actor) { const system = actor?.system ?? {}; if (Array.isArray(system.sauvegardes)) { const value = this.readNumber(system.sauvegardes[4]); if (Number.isFinite(value) && value > 0) return value; } return this.readNumber(system.sauvegarde_sortileges, system.sauvegarde_sorts, system.sauvegardes?.sortileges, system.sauvegardes?.sorts, system.saves?.sorts, system.calculatedSaves?.sorts, system.jp_sort, system.jp_sorts, system.jp?.sorts, system.jp?.sortileges); }
  static async rollDamageSave(actor, bonus = 0) { const threshold = this.getDamageSaveThreshold(actor); if (!Number.isFinite(threshold) || threshold <= 0) return { canRoll: false, threshold: NaN, total: 0, success: false, bonus: Number(bonus) || 0 }; const value = Number(bonus) || 0, formula = value ? `1d20${value >= 0 ? "+" : ""}${value}` : "1d20", roll = await new Roll(formula).evaluate({ async: true }); if (game.dice3d) await game.dice3d.showForRoll(roll); const total = Number(roll.total) || 0; return { canRoll: true, threshold, total, success: total >= threshold, bonus: value, roll }; }
  static escapeChatHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
  static async createDamageResistanceChat(actor, result) { if (!result?.applied || typeof ChatMessage === "undefined") return; const title = result.naturalProtection ? `PROTECTION CONTRE LE ${String(result.element ?? "").toUpperCase()} NATUREL` : `RÉSISTANCE AU ${String(result.element ?? "").toUpperCase()}`, rule = result.naturalProtection ? `Température déclarée : ${result.context.temperature} °C. Protection active jusqu’à ${result.naturalLimit} °C.` : result.save?.canRoll ? `Jet de protection : ${result.save.total} / seuil ${result.save.threshold}, bonus ${result.save.bonus >= 0 ? "+" : ""}${result.save.bonus}. ${result.save.success ? "Dégâts réduits au quart." : "Dégâts réduits de moitié."}` : "Jet de protection indisponible : dégâts réduits de moitié.", escape = this.escapeChatHtml; await ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor }), content: `<div class="add2e-chat-card add2e-damage-resistance-card" style="font-family:var(--font-primary);background:#eef7ff;border:1px solid #5aa3d8;border-radius:8px;padding:9px;color:#15344a;"><div style="font-weight:900;color:#1f6f9f;font-size:1.05em;margin-bottom:5px;">${escape(title)}</div><div><b>${escape(actor?.name ?? "La cible")}</b> bénéficie d’une protection active.</div><div style="margin-top:5px;">${escape(rule)}</div><div style="margin-top:5px;font-weight:800;">Dégâts : <b>${result.original}</b> → <b>${result.amount}</b></div></div>`, ...(CONST.CHAT_MESSAGE_STYLES ? { style: CONST.CHAT_MESSAGE_STYLES.OTHER } : { type: CONST.CHAT_MESSAGE_TYPES?.OTHER ?? 0 }) }); }
  static async resolveIncomingDamage(actor, { amount = 0, type = "", details = "", chat = true } = {}) { const original = Math.max(0, Number(amount) || 0); if (!actor || original <= 0) return { amount: original, applied: false, original }; const context = this.getDamageContext(type, details); if (!context.element) return { amount: original, applied: false, original, context }; const tags = this.getActiveTags(actor), naturalLimit = this.getNaturalTemperatureLimit(tags, context.element); if (context.natural && Number.isFinite(context.temperature) && Number.isFinite(naturalLimit) && context.temperature >= naturalLimit) { const result = { amount: 0, applied: true, original, element: context.element, context, naturalProtection: true, naturalLimit, save: null }; if (chat) await this.createDamageResistanceChat(actor, result); return result; } const rule = this.getDamageResistanceRule(actor, context.element); if (!rule.found) return { amount: original, applied: false, original, context }; const save = await this.rollDamageSave(actor, rule.bonus), multiplier = save.canRoll && save.success ? rule.succeededMultiplier : rule.failedMultiplier, reduced = Math.max(1, Math.floor(original * multiplier)), result = { amount: reduced, applied: true, original, element: context.element, context, rule, save, naturalProtection: false }; if (chat) await this.createDamageResistanceChat(actor, result); return result; }
  static getBonusTouche(actor, typeArme) { const normalized = this.normalizeKey(typeArme); if (!normalized) return 0; let bonus = 0; for (const tag of this.getActiveTags(actor)) { if (!tag.startsWith("bonus_touche:")) continue; const [, weapon, value] = tag.split(":"); if (this.normalizeKey(weapon) === normalized) bonus += Number(value) || 0; } return bonus; }
  static getBonusToucheVs(actor, typeCible) { const normalized = this.normalizeKey(typeCible); let bonus = 0; for (const tag of this.getActiveTags(actor)) { if (!tag.startsWith("bonus_touche_vs:")) continue; const [, target, value] = tag.split(":"); if (this.normalizeKey(target) === normalized) bonus += Number(value) || 0; } return bonus; }
  static getActorClassSystem(actor) { return actor?.items?.find?.(item => String(item.type || "").toLowerCase() === "classe")?.system ?? actor?.system?.details_classe ?? null; }
  static isMonk(actor) { const classSystem = this.getActorClassSystem(actor), label = this.normalizeKey(classSystem?.label || classSystem?.name || classSystem?.nom || actor?.system?.classe || ""); return label.includes("moine") || this.hasTag(actor, "classe:moine"); }
  static getClassProgressionEntry(actor, field = "progression") { const classSystem = this.getActorClassSystem(actor), level = this.getActorLevel(actor), progression = classSystem?.[field] ?? classSystem?.progression ?? []; if (!Array.isArray(progression) || !progression.length) return null; return progression.find(entry => Number(entry?.niveau ?? entry?.level) === level) ?? progression[Math.max(0, Math.min(progression.length - 1, level - 1))] ?? null; }
  static getMonkProgression(actor) { return this.isMonk(actor) ? this.getClassProgressionEntry(actor, "monkProgression") ?? this.getClassProgressionEntry(actor, "progression") : null; }
  static getMonkArmorClass(actor) { const value = Number(this.getMonkProgression(actor)?.monkAC ?? this.getMonkProgression(actor)?.caMoine ?? this.getMonkProgression(actor)?.ca_moine); return Number.isFinite(value) ? value : null; }
  static getMonkMove(actor) { const value = Number(this.getMonkProgression(actor)?.move ?? this.getMonkProgression(actor)?.movement ?? this.getMonkProgression(actor)?.mouvement); return Number.isFinite(value) ? value : null; }
  static getMonkOpenDoors(actor) { const value = Number(this.getMonkProgression(actor)?.openDoors ?? this.getMonkProgression(actor)?.ouvrir_portes); return Number.isFinite(value) ? value : null; }
  static getMonkUnarmedDamage(actor) { const progression = this.getMonkProgression(actor); return String(progression?.unarmedDamage ?? progression?.main_nue ?? progression?.damage ?? "").trim(); }
  static getMonkAttacksPerRound(actor) { const progression = this.getMonkProgression(actor); return String(progression?.attacksPerRound ?? progression?.attaquesParRound ?? "").trim(); }
  static getMonkStunParalyze(actor) { const progression = this.getMonkProgression(actor), value = Number(progression?.stunParalyze ?? progression?.etourdissement ?? progression?.paralysie); return Number.isFinite(value) ? value : 0; }
  static getMonkSlowFall(actor) { const progression = this.getMonkProgression(actor), value = Number(progression?.slowFall ?? progression?.chute_ralentie); return Number.isFinite(value) ? value : 0; }
  static getMonkSelfHealPerDay(actor) { const progression = this.getMonkProgression(actor), value = Number(progression?.selfHealPerDay ?? progression?.auto_soin); return Number.isFinite(value) ? value : 0; }
  static getMonkWeaponDamageBonus(actor) { const progression = this.getMonkProgression(actor), value = Number(progression?.monkWeaponDamageBonus ?? progression?.bonusDegatsArme ?? progression?.bonus_degats_arme); return Number.isFinite(value) ? value : (this.isMonk(actor) ? Math.floor(this.getActorLevel(actor) / 2) : 0); }
  static hasMonkDiseaseImmunity(actor) { return this.hasImmunity(actor, "maladie"); }
  static getMonkProgressionTags(actor) { const progression = this.getMonkProgression(actor); return progression ? this.toArray(progression.tags).map(tag => this.normalizeTag(tag)).filter(Boolean) : []; }
  static getMonkResistCharmSuggestion(actor) { const progression = this.getMonkProgression(actor), value = Number(progression?.resistCharmSuggestion ?? progression?.resistance_charme_suggestion); return Number.isFinite(value) ? value : 0; }
  static getMonkResistESP(actor) { const progression = this.getMonkProgression(actor), value = Number(progression?.resistESP ?? progression?.resistance_esp); return Number.isFinite(value) ? value : 0; }
  static hasMonkQuiveringPalm(actor) { const progression = this.getMonkProgression(actor); return !!progression?.quiveringPalm || this.hasTag(actor, "moine:paume_palpitante") || this.hasTag(actor, "paume_palpitante"); }
  static getMonkSummary(actor) { const progression = this.getMonkProgression(actor); if (!progression) return null; return { level: this.getActorLevel(actor), title: progression.title ?? "", armorClass: this.getMonkArmorClass(actor), move: this.getMonkMove(actor), openDoors: this.getMonkOpenDoors(actor), unarmedDamage: this.getMonkUnarmedDamage(actor), weaponDamageBonus: this.getMonkWeaponDamageBonus(actor), attacksPerRound: this.getMonkAttacksPerRound(actor), stunParalyze: this.getMonkStunParalyze(actor), slowFall: this.getMonkSlowFall(actor), selfHealPerDay: this.getMonkSelfHealPerDay(actor), resistCharmSuggestion: this.getMonkResistCharmSuggestion(actor), resistESP: this.getMonkResistESP(actor), quiveringPalm: this.hasMonkQuiveringPalm(actor), activeCapabilities: this.getActiveClassFeatures(actor) }; }
  static analyze(actor, action = {}) { const tags = this.getActiveTags(actor), out = {}; if (action.type === "spell" && String(action.name || "").toLowerCase().includes("missile magique") && tags.includes("immunite:missile_magique")) out.immunise = true; if (action.type === "attaque") { const fixed = this.getConditionalFixedCA(actor, { sousType: action.sousType, frontale: !!action.frontale, type: action.type, source: action.source }); if (fixed.ca !== null) out.ca_fixe = fixed.ca; out.ca_fixe_details = fixed; out.bonus_ca = this.getCABonus(actor, action); } if (action.type === "save") { let bonus = 0; if (action.frontale) bonus += this.getSaveBonusFrontal(actor); if (action.vsType) bonus += this.getSaveBonusVs(actor, action.vsType) + this.getBonusSaveConstitution(actor, action.vsType); if (bonus !== 0) out.bonus_save = (out.bonus_save || 0) + bonus; } if (action.type === "moine" || action.type === "monk") out.moine = this.getMonkSummary(actor); if (tags.includes("camouflage")) out.camouflage = true; return out; }
  static getInfravision(actor) { let best = 0; for (const tag of this.getActiveTags(actor)) { if (!tag.startsWith("infravision:")) continue; const value = Number(tag.split(":")[1]) || 0; if (value > best) best = value; } return best; }
}

globalThis.Add2eEffectsEngine = Add2eEffectsEngine;
